# Generated by Django 4.0 on 2021-12-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key1', models.CharField(max_length=200)),
                ('key2', models.CharField(max_length=200)),
                ('failure', models.TextField()),
                ('reason', models.TextField()),
            ],
        ),
    ]
