# Generated by Django 4.0 on 2021-12-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultparser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleqa',
            name='project',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AddField(
            model_name='simpleqa',
            name='test_suite',
            field=models.CharField(default='CTS', max_length=10),
        ),
    ]
